### ISSUE TITLE
测试不成功

### ISSUE THREAD

**Issue by kugua233** [lqzhgood/Rss2Weibo#1]
微博开放平台 【应用信息】 添加 【安全域名】微博上这一条是必须要写吗？没有找到【安全域名】，只有高级信息里的【安全IP】

**Comment by lqzhgood** [comment]
【应用信息】-【基本信息】-【应用基本信息】-【安全域名】
![image](https://user-images.githubusercontent.com/9134671/60392305-9c08c000-9b32-11e9-9995-63f648ca383e.png)
