### ISSUE TITLE
问个比较傻的问题，从哪儿看到转过来的微博？

### ISSUE THREAD

**Issue by kh9n** [lqzhgood/Rss2Weibo#2]
设置好在本地跑起来了
![image](https://user-images.githubusercontent.com/3656667/127869071-3131aa76-ba84-4653-8c27-602a97b66815.png)

**Comment by lqzhgood** [comment]
没懂你的问题~

这是是 **Rss** --> **微博**， 不是 **微博** -->  Rss。
你在 **Rss** 更新 abc ， 就能在 **微博** 看到 abc
